Repository baedal-legend/foody, pull requests merged in 2024-08, with the labels that each got.

#8 config(#5): 데이터 감사를 위한 Auditing fields 정의
  src/main/java/com/sparta/baedallegend/global/config/Auditable.java
Labels: enhancement

#11 config: JPA Auditing 설정 및 soft delete 처리 부 구현
  src/main/java/com/sparta/baedallegend/global/config/jpa/Auditable.java
  src/main/java/com/sparta/baedallegend/global/config/jpa/JpaConfig.java
Labels: config

#13 feat: Shop 초기 세팅
  src/main/java/com/sparta/baedallegend/shop/controller/ShopController.java
  src/main/java/com/sparta/baedallegend/shop/domain/Shop.java
  src/main/java/com/sparta/baedallegend/shop/domain/ShopStatus.java
  src/main/java/com/sparta/baedallegend/shop/repo/ShopRepo.java
  src/main/java/com/sparta/baedallegend/shop/service/ShopService.java
Labels: feat

#14 feat: Menu 초기 세팅
  src/main/java/com/sparta/baedallegend/menu/controller/MenuController.java
  src/main/java/com/sparta/baedallegend/menu/domain/Menu.java
  src/main/java/com/sparta/baedallegend/menu/repo/MenuRepo.java
  src/main/java/com/sparta/baedallegend/menu/service/MenuService.java
Labels: feat

#15 feat: Category 초기 세팅
  src/main/java/com/sparta/baedallegend/category/controller/CategoryController.java
  src/main/java/com/sparta/baedallegend/category/domain/Category.java
  src/main/java/com/sparta/baedallegend/category/repo/CategoryRepo.java
  src/main/java/com/sparta/baedallegend/category/service/CategoryService.java
Labels: feat

#20 feat: User 초기 세팅
  src/main/java/com/sparta/baedallegend/user/controller/UserController.java
  src/main/java/com/sparta/baedallegend/user/domain/Role.java
  src/main/java/com/sparta/baedallegend/user/domain/User.java
  src/main/java/com/sparta/baedallegend/user/repo/UserRepo.java
  src/main/java/com/sparta/baedallegend/user/service/UserService.java
Labels: feat

#28 Config: profiles 별 Application 구동을 위한 환경 설정 구성
  build.gradle
  src/main/java/com/sparta/baedallegend/BaedalLegendApp.java
  src/main/resources/application.properties
  src/main/resources/application.yml
  src/main/resources/properties/datasource.yml
  src/main/resources/properties/jpa.yml
  src/test/java/com/sparta/baedallegend/BaedalLegendAppTests.java
Labels: test, build, config, style

#23 build: Local 환경의 postgreSQL 환경 설정 구성
  .gitignore
  README.md
  docker-compose.yml
Labels: build, config

#35 docs: Pull Request Template 추가
  .github/PULL_REQUEST_TEMPLATE.md
Labels: docs

#36 config: Code Convention 통일 및 자동화를 위한 google java convention 설정 적용
  .editorconfig
  .gitattributes
  .gitignore
  conventions/intellij-java-google-style.xml
Labels: config

#42 docs(#29): PR Template 수정
  .github/PULL_REQUEST_TEMPLATE.md
Labels: docs

#21 Feat: Order 초기세팅
  src/main/java/com/sparta/baedallegend/order/controller/OrderController.java
  src/main/java/com/sparta/baedallegend/order/domain/Order.java
  src/main/java/com/sparta/baedallegend/order/domain/OrderStatus.java
  src/main/java/com/sparta/baedallegend/order/repo/OrderRepo.java
  src/main/java/com/sparta/baedallegend/order/service/OrderService.java
Labels: feat

#41 feat: 고객 계층 회원 가입 API 구현
  build.gradle
  docs/client/user-api.http
  src/main/java/com/sparta/baedallegend/auth/controller/AuthController.java
  src/main/java/com/sparta/baedallegend/auth/controller/model/SignUpRequest.java
  src/main/java/com/sparta/baedallegend/auth/controller/model/SignUpType.java
  src/main/java/com/sparta/baedallegend/auth/exception/AuthErrorCode.java
  src/main/java/com/sparta/baedallegend/auth/exception/AuthException.java
  src/main/java/com/sparta/baedallegend/auth/service/CreateUserService.java
  src/main/java/com/sparta/baedallegend/auth/service/CustomerCreateService.java
  src/main/java/com/sparta/baedallegend/auth/service/SignUpFacade.java
  src/main/java/com/sparta/baedallegend/global/config/security/PasswordEncoderConfig.java
  src/main/java/com/sparta/baedallegend/global/config/security/SecurityConfig.java
  src/main/java/com/sparta/baedallegend/global/config/utils/ResponseEntityUtils.java
  src/main/java/com/sparta/baedallegend/global/config/utils/UriComponentUtils.java
  src/main/java/com/sparta/baedallegend/user/domain/Role.java
  src/main/java/com/sparta/baedallegend/user/domain/User.java
  src/main/java/com/sparta/baedallegend/user/domain/wrap/Password.java
  src/main/java/com/sparta/baedallegend/user/repo/UserRepo.java
  src/test/java/com/sparta/baedallegend/auth/controller/AuthControllerTest.java
  src/test/java/com/sparta/baedallegend/base/TestBase.java
  src/test/java/com/sparta/baedallegend/base/WebMvcTestBase.java
Labels: feat, enhance, test, build, config

#45 Fix/#44 edit local profile database connections info
  docker-compose.yml
  src/main/resources/properties/datasource.yml
Labels: fix

#46 feat: Shop 생성 API 구현
  docs/client/shop-create-api.http
  src/main/java/com/sparta/baedallegend/category/domain/Category.java
  src/main/java/com/sparta/baedallegend/category/repo/CategoryRepo.java
  src/main/java/com/sparta/baedallegend/global/config/security/SecurityConfig.java
  src/main/java/com/sparta/baedallegend/region/repo/RegionRepo.java
  src/main/java/com/sparta/baedallegend/shop/controller/ShopController.java
  src/main/java/com/sparta/baedallegend/shop/controller/dto/CreateShopRequest.java
  src/main/java/com/sparta/baedallegend/shop/domain/Shop.java
  src/main/java/com/sparta/baedallegend/shop/domain/ShopCategory.java
  src/main/java/com/sparta/baedallegend/shop/repo/ShopCategoryRepo.java
  src/main/java/com/sparta/baedallegend/shop/service/ShopService.java
Labels: feat

#26 feat: Payment 초기 세팅
  src/main/java/com/sparta/baedallegend/payment/controller/PaymentController.java
  src/main/java/com/sparta/baedallegend/payment/domain/Payment.java
  src/main/java/com/sparta/baedallegend/payment/repo/PaymentRepo.java
  src/main/java/com/sparta/baedallegend/payment/service/PaymentService.java
Labels: feat

#51 docs: pr template 간소화
  .github/PULL_REQUEST_TEMPLATE.md
Labels: docs

#52 build: 파라미터가 바인딩된 실행 쿼리 출력을 위한 p6spy 및 TestContainers 설정
  build.gradle
  src/main/resources/properties/datasource.yml
  src/main/resources/properties/jpa.yml
  src/test/java/com/sparta/baedallegend/BaedalLegendAppTests.java
  src/test/java/com/sparta/baedallegend/base/JpaTestBase.java
  src/test/java/com/sparta/baedallegend/config/P6spySqlFormatConfig.java
  src/test/java/com/sparta/baedallegend/user/fixture/UserFixtureGenerator.java
  src/test/java/com/sparta/baedallegend/user/repo/UserRepoTest.java
Labels: test, build, config

#53 docs: 명확하지 않은 표현 개선
  .github/PULL_REQUEST_TEMPLATE.md
Labels: docs

#54 feat: JWT 검증 필터 구현
  src/main/java/com/sparta/baedallegend/auth/domain/FoodyPrincipal.java
  src/main/java/com/sparta/baedallegend/auth/exception/AuthErrorCode.java
  src/main/java/com/sparta/baedallegend/auth/filter/JwtFilter.java
  src/main/java/com/sparta/baedallegend/auth/service/AuthenticationService.java
  src/main/java/com/sparta/baedallegend/auth/utils/jwt/JwtProvider.java
  src/main/java/com/sparta/baedallegend/auth/utils/jwt/JwtResolver.java
  src/main/java/com/sparta/baedallegend/auth/utils/jwt/JwtUtils.java
  src/main/java/com/sparta/baedallegend/auth/utils/jwt/RequestHeaderUtils.java
  src/main/java/com/sparta/baedallegend/global/config/security/AuthorizationConfig.java
  src/main/java/com/sparta/baedallegend/global/config/security/SecurityConfig.java
Labels: feat, enhance, config

#56 feat: 손쉬운 현재 로그인 사용자 정보 접근을 위한 Custom annotation 정의
  docs/client/auth-api.http
  docs/client/user-api.http
  src/main/java/com/sparta/baedallegend/auth/domain/FoodyPrincipal.java
  src/main/java/com/sparta/baedallegend/auth/filter/JwtFilter.java
  src/main/java/com/sparta/baedallegend/auth/service/AuthenticationService.java
  src/main/java/com/sparta/baedallegend/auth/utils/jwt/JwtProvider.java
  src/main/java/com/sparta/baedallegend/auth/utils/jwt/JwtResolver.java
  src/main/java/com/sparta/baedallegend/global/config/annotations/LoginUser.java
  src/main/java/com/sparta/baedallegend/user/controller/UserController.java
  src/main/java/com/sparta/baedallegend/user/controller/model/UserResponse.java
  src/main/java/com/sparta/baedallegend/user/domain/User.java
  src/main/java/com/sparta/baedallegend/user/exception/UserErrorCode.java
  src/main/java/com/sparta/baedallegend/user/exception/UserException.java
  src/main/java/com/sparta/baedallegend/user/service/UserService.java
Labels: feat, fix

#62 feat: Shop 전체 조회 API
  docs/client/shop-api.http
  src/main/java/com/sparta/baedallegend/global/config/security/SecurityConfig.java
  src/main/java/com/sparta/baedallegend/shop/controller/ShopController.java
  src/main/java/com/sparta/baedallegend/shop/controller/dto/FindAllShopResponse.java
  src/main/java/com/sparta/baedallegend/shop/repo/ShopRepo.java
  src/main/java/com/sparta/baedallegend/shop/service/ShopService.java
Labels: feat

#59 feat: #58 User Entity의 Auditor 정의 및 CreatedBy 설정 처리 부 구현
  src/main/java/com/sparta/baedallegend/auth/service/CustomerCreateService.java
  src/main/java/com/sparta/baedallegend/global/config/jpa/Auditable.java
  src/main/java/com/sparta/baedallegend/global/config/jpa/CommonAuditFields.java
  src/main/java/com/sparta/baedallegend/user/domain/User.java
  src/main/java/com/sparta/baedallegend/user/domain/auditor/UserAuditable.java
  src/main/resources/properties/jpa.yml
Labels: enhance, config

#60 config: 데이터 감사 및 추적을 위한 Auditor 값 자동 설정 Configuration 구성
  src/main/java/com/sparta/baedallegend/global/config/jpa/AuditorAwareConfig.java
Labels: config

#65 feat: Shop 단일 조회 API
  docs/client/shop-api.http
  src/main/java/com/sparta/baedallegend/menu/domain/MenuStatus.java
  src/main/java/com/sparta/baedallegend/menu/repo/MenuRepo.java
  src/main/java/com/sparta/baedallegend/shop/controller/ShopController.java
  src/main/java/com/sparta/baedallegend/shop/controller/dto/ReadOneShopMenuResponse.java
  src/main/java/com/sparta/baedallegend/shop/controller/dto/ReadOneShopRequest.java
  src/main/java/com/sparta/baedallegend/shop/controller/dto/ReadOneShopResponse.java
  src/main/java/com/sparta/baedallegend/shop/exception/ShopErrorCode.java
  src/main/java/com/sparta/baedallegend/shop/exception/ShopException.java
  src/main/java/com/sparta/baedallegend/shop/service/ShopService.java
Labels: feat

#71 fix: 공통 설정 부 버그 수정
  src/main/java/com/sparta/baedallegend/auth/service/CustomerCreateService.java
  src/main/java/com/sparta/baedallegend/global/config/exception/GlobalErrorCode.java
  src/main/java/com/sparta/baedallegend/global/config/exception/GlobalErrorResponse.java
  src/main/java/com/sparta/baedallegend/global/config/exception/GlobalExceptionHandler.java
  src/main/java/com/sparta/baedallegend/global/config/jpa/CommonAuditFields.java
  src/main/java/com/sparta/baedallegend/user/domain/User.java
  src/main/java/com/sparta/baedallegend/user/domain/auditor/UserAuditable.java
  src/main/resources/application.yml
  src/main/resources/properties/logging.yml
  src/test/java/com/sparta/baedallegend/base/JpaTestBase.java
  src/test/java/com/sparta/baedallegend/user/repo/UserRepoTest.java
Labels: fix

#77 feat: 회원 타입 조회 API 구현
  docs/client/auth-api.http
  src/main/java/com/sparta/baedallegend/auth/controller/AuthController.java
  src/main/java/com/sparta/baedallegend/auth/controller/model/SignUpRequest.java
  src/main/java/com/sparta/baedallegend/auth/controller/model/SignUpType.java
  src/main/java/com/sparta/baedallegend/auth/controller/model/SignUpTypeDto.java
  src/main/java/com/sparta/baedallegend/auth/controller/model/SignUpTypeResponse.java
  src/main/java/com/sparta/baedallegend/auth/service/CreateUserService.java
  src/main/java/com/sparta/baedallegend/auth/service/CustomerCreateService.java
  src/main/java/com/sparta/baedallegend/global/config/security/SecurityConfig.java
  src/main/java/com/sparta/baedallegend/user/domain/Role.java
  src/main/java/com/sparta/baedallegend/user/domain/User.java
  src/test/java/com/sparta/baedallegend/auth/controller/AuthControllerTest.java
  src/test/java/com/sparta/baedallegend/base/WebMvcTestBase.java
  src/test/java/com/sparta/baedallegend/user/fixture/UserFixtureGenerator.java
Labels: feat

#74 feat: 회원 탈퇴 API 구현 및 TC 작성
  docs/client/user-api.http
  src/main/java/com/sparta/baedallegend/user/controller/UserController.java
  src/main/java/com/sparta/baedallegend/user/service/UserService.java
Labels: feat, enhance

#79 feat: 사장님/관리자 회원 가입 API 구현 및 TC 작성
  docs/client/auth-api.http
  src/main/java/com/sparta/baedallegend/auth/service/SignUpFacade.java
  src/main/java/com/sparta/baedallegend/auth/service/strategy/CreateCustomerStrategy.java
  src/main/java/com/sparta/baedallegend/auth/service/strategy/CreateMasterStrategy.java
  src/main/java/com/sparta/baedallegend/auth/service/strategy/CreateOwnerStrategy.java
  src/main/java/com/sparta/baedallegend/auth/service/strategy/CreateUserService.java
  src/main/java/com/sparta/baedallegend/user/domain/Role.java
  src/test/java/com/sparta/baedallegend/auth/controller/AuthControllerTest.java
Labels: feat, enhance, test

#69 feat: 가게 검색 API
  docs/client/shop-api.http
  src/main/java/com/sparta/baedallegend/menu/repo/MenuRepo.java
  src/main/java/com/sparta/baedallegend/shop/controller/ShopController.java
  src/main/java/com/sparta/baedallegend/shop/controller/dto/SearchShopResponse.java
  src/main/java/com/sparta/baedallegend/shop/repo/ShopRepo.java
  src/main/java/com/sparta/baedallegend/shop/service/ShopService.java
Labels: feat

#87 feat: Shop Entity Auditor 적용 및 Auditable 상수 설정
  docs/client/shop-api.http
  src/main/java/com/sparta/baedallegend/domains/shop/domain/Shop.java
  src/main/java/com/sparta/baedallegend/global/config/jpa/audit/CommonAuditFields.java
Labels: feat

#84 build: Jib을 이용한 application dockerizing
  README.md
  build.gradle
  docker-compose.yml
  docs/build.sh
  docs/service-down.sh
  docs/service-up.sh
  foody-compose.yml
Labels: build

#89 feat: 메뉴 전체 조회 API
  docs/client/menu-api.http
  src/main/java/com/sparta/baedallegend/domains/menu/controller/MenuController.java
  src/main/java/com/sparta/baedallegend/domains/menu/controller/dto/FindAllMenuResponse.java
  src/main/java/com/sparta/baedallegend/domains/menu/repo/MenuRepo.java
  src/main/java/com/sparta/baedallegend/domains/menu/service/MenuService.java
Labels: feat, fix

#91 build: query-dsl 설정 추가
  .gitignore
  build.gradle
  docs/client/user-api.http
  src/main/java/com/sparta/baedallegend/domains/user/controller/UserController.java
  src/main/java/com/sparta/baedallegend/domains/user/controller/model/UserResponse.java
  src/main/java/com/sparta/baedallegend/domains/user/repo/UserQueryRepo.java
  src/main/java/com/sparta/baedallegend/domains/user/service/UserService.java
  src/main/java/com/sparta/baedallegend/global/config/querydsl/QueryDslConfig.java
  src/test/java/com/sparta/baedallegend/domains/auth/controller/AuthControllerTest.java
  src/test/java/com/sparta/baedallegend/domains/user/repo/UserQueryRepoTest.java
  src/test/java/com/sparta/baedallegend/domains/user/repo/UserRepoTest.java
  src/test/java/com/sparta/baedallegend/global/base/JpaTestBase.java
  src/test/java/com/sparta/baedallegend/global/base/TestBase.java
  src/test/java/com/sparta/baedallegend/global/base/WebMvcTestBase.java
  src/test/java/com/sparta/baedallegend/global/config/P6spySqlFormatConfig.java
  src/test/java/com/sparta/baedallegend/global/config/QueryDslTestConfig.java
  src/test/java/com/sparta/baedallegend/global/fixture/UserFixtureGenerator.java
Labels: enhance, test, build, config
